### PR TITLE
feat: add secContext options

### PR DESCRIPTION
**Pull request by Demonsthere**
- Expose securityContext fields for all containers. Not adding any default fields for now :)
- Add simple GHA to test if the chart can be installed

### CODE REVIEW

**Comment by rueian** [comment]
Hi @Demonsthere, thank you very much! It looks good to me.

**Comment by Demonsthere** [comment]
Ups, yeah :D Still working on that, moving to draft for now

**Comment by Demonsthere** [comment]
Now it's working as intended 😉

**Comment by rueian** [comment]
Thanks!

**Pull request merged**
